//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res_pl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res_pl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Resource.Res-pl", typeof(Res_pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stan konta.
        /// </summary>
        internal static string BankAccountConditionListViewHeader {
            get {
                return ResourceManager.GetString("BankAccountConditionListViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer rachunku.
        /// </summary>
        internal static string BankAccountNumberListViewHeader {
            get {
                return ResourceManager.GetString("BankAccountNumberListViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przelew zewnętrzny.
        /// </summary>
        internal static string ExternalTransfer {
            get {
                return ResourceManager.GetString("ExternalTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota.
        /// </summary>
        internal static string HistoryAmountListViewHeader {
            get {
                return ResourceManager.GetString("HistoryAmountListViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string HistoryDateListViewHeader {
            get {
                return ResourceManager.GetString("HistoryDateListViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Od.
        /// </summary>
        internal static string HistoryFromListViewHeader {
            get {
                return ResourceManager.GetString("HistoryFromListViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operacja.
        /// </summary>
        internal static string HistoryOperationTypeListViewHeader {
            get {
                return ResourceManager.GetString("HistoryOperationTypeListViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        internal static string HistoryToListViewHeader {
            get {
                return ResourceManager.GetString("HistoryToListViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przelew wewnętrzny.
        /// </summary>
        internal static string InternalTransfer {
            get {
                return ResourceManager.GetString("InternalTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny numer konta bankowego nadawcy.
        /// </summary>
        internal static string InvalidBankAccountFrom {
            get {
                return ResourceManager.GetString("InvalidBankAccountFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawny numer konta bankowego odbiorcy.
        /// </summary>
        internal static string InvalidBankAccountTo {
            get {
                return ResourceManager.GetString("InvalidBankAccountTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj konto.
        /// </summary>
        internal static string MainCreateAccount {
            get {
                return ResourceManager.GetString("MainCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpłać pieniądze.
        /// </summary>
        internal static string MainDepositMoney {
            get {
                return ResourceManager.GetString("MainDepositMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historia operacji.
        /// </summary>
        internal static string MainHistory {
            get {
                return ResourceManager.GetString("MainHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona startowa.
        /// </summary>
        internal static string MainHome {
            get {
                return ResourceManager.GetString("MainHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zalogowano jako: .
        /// </summary>
        internal static string MainLoggedAs {
            get {
                return ResourceManager.GetString("MainLoggedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypłać pieniądze.
        /// </summary>
        internal static string MainWithdrawMoney {
            get {
                return ResourceManager.GetString("MainWithdrawMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proszę wypełnić polę &quot;Tytuł&quot;.
        /// </summary>
        internal static string NoTitleError {
            get {
                return ResourceManager.GetString("NoTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto odbiory i nadawcy nie mogą być takie same.
        /// </summary>
        internal static string SameFromToBankAccounts {
            get {
                return ResourceManager.GetString("SameFromToBankAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwota:.
        /// </summary>
        internal static string TransferAmount {
            get {
                return ResourceManager.GetString("TransferAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrealizuj przelew.
        /// </summary>
        internal static string TransferExecuteTransfer {
            get {
                return ResourceManager.GetString("TransferExecuteTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto nadawcy:.
        /// </summary>
        internal static string TransferFrom {
            get {
                return ResourceManager.GetString("TransferFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wstecz.
        /// </summary>
        internal static string TransferGoBack {
            get {
                return ResourceManager.GetString("TransferGoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł:.
        /// </summary>
        internal static string TransferTitle {
            get {
                return ResourceManager.GetString("TransferTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konto odbiorcy:.
        /// </summary>
        internal static string TransferTo {
            get {
                return ResourceManager.GetString("TransferTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna kwota przelewu.
        /// </summary>
        internal static string WrongAmount {
            get {
                return ResourceManager.GetString("WrongAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawn login i/lub hasło.
        /// </summary>
        internal static string WrongLoginParameters {
            get {
                return ResourceManager.GetString("WrongLoginParameters", resourceCulture);
            }
        }
    }
}
